### ISSUE TITLE
סקאלת ציר זמן הפוכה

### ISSUE THREAD

**Issue by emrib** [hasadna/datacity#11]
<img width="478" alt="image" src="https://github.com/hasadna/datacity/assets/76155903/94edf251-9afc-4026-9d85-8411d15482f4">
סקאלת ציר הזמן הפוכה בגיאוגרפיה -> שטח השיפוט

**Comment by akariv** [comment]
אני לא רואה את הבעיה

**Comment by emrib** [comment]
2015 בצד ימין

**Comment by emrib** [comment]
טעות שלי. צריך משקפיים כנראה..

**Comment by emrib** [comment]
תודה
